@baseUrl=http://localhost:3000
@id=685b3681-8b6c-4695-bdda-dcb2a0aefff2
@phoneId=c201fbb8-d324-4e77-97a6-80793db1f2c8
# @name createAddressFromUser
POST {{baseUrl}}/phones
Content-Type: application/json

{
    "user_id": "{{id}}",
    "country_code": "1",
    "number": "1234567890",
    "extension": "123",
    "type": "mobile",
    "is_primary": true
}
###

# @name updatePhone
PATCH {{baseUrl}}/phones/{{phoneId}}
Content-Type: application/json

{
    "number": "0987654321"
}

###

# @name getUsersPhones
GET {{baseUrl}}/phones/users-phone/{{id}}

###

# @name removePhoneFromUser
DELETE {{baseUrl}}/phones/{{phoneId}}